const quotes = [
    { text: "Time is the friend of wonderful businesses, the enemy of mediocre ones", author: "Warren Buffett", category: "Investment Philosophy" },
    { text: "Risk comes from not knowing what you're doing", author: "Warren Buffett", category: "Risk Management" },
    { text: "Be fearful when others are greedy and greedy when others are fearful", author: "Warren Buffett", category: "Market Sentiment" },
    { text: "The best investment you can make is in yourself", author: "Warren Buffett", category: "Self Investment" },
    { text: "Price is what you pay, value is what you get", author: "Warren Buffett", category: "Value Investing" },
    { text: "Never invest in a business you cannot understand", author: "Warren Buffett", category: "Investment Philosophy" },
    { text: "If you won't own a stock for ten years, don't own it for ten minutes", author: "Warren Buffett", category: "Long-term Investing" },
    { text: "Only when the tide goes out do you discover who's been swimming naked", author: "Warren Buffett", category: "Market Reality" },
    { text: "Rule No.1: Never lose money. Rule No.2: Never forget rule No.1", author: "Warren Buffett", category: "Risk Management" },
    { text: "The chains of habit are too light to be felt until they are too heavy to be broken", author: "Warren Buffett", category: "Behavioral Habits" },
    { text: "Acquiring wisdom is a moral duty", author: "Charlie Munger", category: "Life Wisdom" },
    { text: "Invert, always invert", author: "Charlie Munger", category: "Thinking Models" },
    { text: "Macro is what we must accept; micro is what we can do something about", author: "Charlie Munger", category: "Investment Philosophy" },
    { text: "Investing is a waiting game", author: "Charlie Munger", category: "Investment Psychology" },
    { text: "Acknowledging ignorance is the beginning of wisdom", author: "Charlie Munger", category: "Life Wisdom" },
    { text: "I have never seen anyone who wasn't smart become wise without reading", author: "Charlie Munger", category: "Learning & Reading" },
    { text: "To get what you want, you have to deserve what you want", author: "Charlie Munger", category: "Self Improvement" },
    { text: "My success comes from one thing: I see a little further ahead", author: "Charlie Munger", category: "Vision" },
    { text: "The most important thing is to remember your circle of competence", author: "Charlie Munger", category: "Circle of Competence" },
    { text: "We're not smart, we're just not stupid", author: "Charlie Munger", category: "Wisdom & Humility" },
    { text: "Invest in companies you understand", author: "Peter Lynch", category: "Company Analysis" },
    { text: "The amateur investor's advantage is not having to beat the market", author: "Peter Lynch", category: "Investment Psychology" },
    { text: "Stocks don't know you own them", author: "Peter Lynch", category: "Market Sentiment" },
    { text: "Never invest in any company you can't explain to an 8-year-old", author: "Peter Lynch", category: "Company Analysis" },
    { text: "The perfect portfolio doesn't exist", author: "Peter Lynch", category: "Diversification" },
    { text: "If you have patience, stocks will definitely go up", author: "Peter Lynch", category: "Patient Investing" },
    { text: "Before buying a stock, consider if you can watch it drop 50%", author: "Peter Lynch", category: "Risk Tolerance" },
    { text: "Don't rely on anyone to recommend stocks, do your own homework", author: "Peter Lynch", category: "Independent Research" },
    { text: "Stock market declines are as normal as January blizzards", author: "Peter Lynch", category: "Market Declines" },
    { text: "The biggest risk in the stock market is not investing at all", author: "Peter Lynch", category: "Investment Necessity" },
    { text: "In the short run, the market is a voting machine; in the long run, it's a weighing machine", author: "Benjamin Graham", category: "Market Sentiment" },
    { text: "The investor's chief problem, and worst enemy, is likely himself", author: "Benjamin Graham", category: "Investment Psychology" },
    { text: "Successful investing requires time, discipline, and patience", author: "Benjamin Graham", category: "Investment Philosophy" },
    { text: "The intelligent investor won't be upset by stock price declines", author: "Benjamin Graham", category: "Investment Psychology" },
    { text: "Margin of safety is the cornerstone of investment success", author: "Benjamin Graham", category: "Margin of Safety" },
    { text: "Investment is based on analysis and promises safety of principal and adequate return", author: "Benjamin Graham", category: "Investment Definition" },
    { text: "Mr. Market is your servant, not your teacher", author: "Benjamin Graham", category: "Market Relationship" },
    { text: "The investor's primary goal should be to avoid major losses", author: "Benjamin Graham", category: "Loss Avoidance" },
    { text: "Find opportunity in others' fear, sense danger in others' greed", author: "Benjamin Graham", category: "Investment Opportunity" },
    { text: "The defensive investor's goal is to avoid serious mistakes or losses", author: "Benjamin Graham", category: "Defensive Investing" },
    { text: "The most important thing isn't what to buy, but at what price to buy", author: "Howard Marks", category: "Value Investing" },
    { text: "You can't predict, but you can prepare", author: "Howard Marks", category: "Risk Management" },
    { text: "Risk control is the foundation of investment success", author: "Howard Marks", category: "Risk Management" },
    { text: "Markets are neither efficient nor completely inefficient", author: "Howard Marks", category: "Market Sentiment" },
    { text: "Superior investing requires second-level thinking", author: "Howard Marks", category: "Thinking Models" },
    { text: "The greatest investment risk is losing capital, not missing gains", author: "Howard Marks", category: "Risk Definition" },
    { text: "Good investing isn't about buying good things, it's about buying well", author: "Howard Marks", category: "Buying Strategy" },
    { text: "Market cycles are one of the most important concepts for investors to understand", author: "Howard Marks", category: "Market Cycles" },
    { text: "Superior investing requires doing what others don't do", author: "Howard Marks", category: "Differentiated Strategy" },
    { text: "The best opportunities usually come at the worst times", author: "Howard Marks", category: "Opportunity Recognition" },
    { text: "Pain plus reflection equals progress", author: "Ray Dalio", category: "Life Wisdom" },
    { text: "Diversification is a free lunch", author: "Ray Dalio", category: "Diversification" },
    { text: "Principles are ways of handling reality", author: "Ray Dalio", category: "Thinking Models" },
    { text: "Embrace reality and deal with it", author: "Ray Dalio", category: "Investment Philosophy" },
    { text: "The biggest failure is not learning from failures", author: "Ray Dalio", category: "Failure Lessons" },
    { text: "Independent thinking is key to successful investing", author: "Ray Dalio", category: "Independent Thinking" },
    { text: "Understanding the economic machine is key to investment success", author: "Ray Dalio", category: "Economic Understanding" },
    { text: "Debt cycles are the main driver of economic fluctuations", author: "Ray Dalio", category: "Debt Cycles" },
    { text: "The best investment opportunities often appear during difficult times", author: "Ray Dalio", category: "Investment Opportunity" },
    { text: "History doesn't repeat, but it rhymes", author: "Ray Dalio", category: "Historical Patterns" },
    { text: "Time is your best friend, impulse is your greatest enemy", author: "John Bogle", category: "Investment Psychology" },
    { text: "Don't look for the needle in the haystack, just buy the haystack", author: "John Bogle", category: "Diversification" },
    { text: "Costs matter, time matters more", author: "John Bogle", category: "Long-term Investing" },
    { text: "Complexity is the enemy of simplicity", author: "John Bogle", category: "Investment Philosophy" },
    { text: "In investing, you get what you don't pay for", author: "John Bogle", category: "Value Investing" },
    { text: "Index funds are the investor's best friend", author: "John Bogle", category: "Index Investing" },
    { text: "Market noise is the investor's enemy", author: "John Bogle", category: "Market Noise" },
    { text: "Low cost is one of the most important factors in investment success", author: "John Bogle", category: "Cost Control" },
    { text: "The stock market is a wealth transfer machine, from the impatient to the patient", author: "John Bogle", "category": "Wealth Transfer" },
    { text: "The investor's greatest enemy is not the market, but the investor himself", author: "John Bogle", category: "Self Awareness" },
    { text: "Buy shares of excellent companies, then forget about them", author: "Philip Fisher", category: "Long-term Investing" },
    { text: "Investing in stocks is, to some extent, investing in management", author: "Philip Fisher", category: "Company Analysis" },
    { text: "If you don't study any companies, your chance of success is zero", author: "Philip Fisher", category: "Company Analysis" },
    { text: "The essence of growth stock investing is finding real growth", author: "Philip Fisher", category: "Growth Investing" },
    { text: "When buying truly excellent growth stocks, timing is far more important than price", author: "Philip Fisher", category: "Timing Selection" },
    { text: "Investing in growth stocks requires enough patience to wait for the harvest", author: "Philip Fisher", category: "Investment Patience" },
    { text: "The best investment opportunities are often where others can't see them", author: "Philip Fisher", category: "Opportunity Discovery" },
    { text: "Excellent management is the key to successful growth stock investing", author: "Philip Fisher", category: "Management Importance" },
    { text: "Concentrating investments in a few excellent stocks is more effective than diversification", author: "Philip Fisher", category: "Concentrated Investing" },
    { text: "Investing in growth stocks requires a long-term vision", author: "Philip Fisher", category: "Long-term Vision" },
    { text: "Compound interest is the eighth wonder of the world", author: "Albert Einstein", category: "Compound Thinking" },
    { text: "Don't put all your eggs in one basket", author: "Investment Wisdom", category: "Diversification" },
    { text: "Buy and hold is the simplest and most effective investment strategy", author: "Investment Wisdom", category: "Long-term Investing" }
];
